# Generated by Django 4.2.6 on 2023-10-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micros', '0005_alter_archivo_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
    ]
